/*
 * Copyright 2019 faddenSoft
 * Copyright 2026 Lydian Scale Software
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using Avalonia.Media;

namespace cp2_avalonia.LibTest {
    /// <summary>
    /// Progress message, with colorful text.  This is generated by the worker thread and
    /// passed to the UI thread.
    /// </summary>
    public class ProgressMessage(string msg, Color color)
    {
        private static readonly Color ZeroColor = Color.FromArgb(0, 0, 0, 0);

        public string Text { get; private set; } = msg;
        public Color Color { get; private set; } = color;
        public bool HasColor => Color.A != 0;

        public ProgressMessage(string msg) : this(msg, ZeroColor) { }
    }
}
